[[collection]]
type = "card_simple"
title = "E-mail"
content = """
<style>
div.email > span:nth-child(1) { display: none;}
div.email > span:nth-child(4) { display: none;}
</style>
<div class="email">johnzl<span>wumbo</span>.<span>d</span>ev@<span>gm</span><span>cats</span>ail.</span>com</div>
"""

[[collection]]
type = "card_simple"
title = "LinkedIn"
link = "https://www.linkedin.com/in/jzl"
content = "linkedin.com/in/jzl"

[[collection]]
type = "card_simple"
title = "Github"
link = "https://github.com/johnzl-777"
content = "johnzl-777"

[[collection]]
type = "card_simple"
title = "ORCID"
link = "https://orcid.org/0009-0005-7557-197X"
content = "0009-0005-7557-197X"

[[collection]]
type = "card_simple"
title = "Google Scholar"
link = "https://scholar.google.com/citations?user=qhZSK24AAAAJ&hl"
content = "John Long"